### ISSUE TITLE
Input selection shows unknown

### ISSUE THREAD

**Issue by marchein** [MrAsterisco/homebridge-hisense-tv#12]
**Describe The Bug:**

Sometimes when I restart homebridge the plugin shows the input selection as "unknown" (see screenshot) and shows the input as devices with which the home app cannot do anything (see other screenshot). 

**To Reproduce:**

This sometimes happens when I restart homebridge and can be "fixed" by restarting homebridge several times. Sometimes it resolves it, sometimes it does not. 

**Expected behavior:**

I should be able to always select the inputs I want and it should be displayed in the home app:
![IMG_0037](https://user-images.githubusercontent.com/4535391/119233503-c3534680-bb29-11eb-86df-2a32c23c8b2d.jpeg)

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
...
        {
            "ifname": "eth0",
            "devices": [
                {
                    "id": "<tvserial>",
                    "name": "Fernseher",
                    "ipaddress": "10.0.11.72",
                    "macaddress": "aa:bb:cc:dd:ee:ff",
                    "sslmode": "default"
                }
            ],
            "platform": "HiSenseTV"
        },
...
```

**Screenshots:**

![IMG_0034](https://user-images.githubusercontent.com/4535391/119233307-b124d880-bb28-11eb-9728-9798c1840f24.jpeg)
![IMG_0035](https://user-images.githubusercontent.com/4535391/119233309-b3873280-bb28-11eb-954c-b280659e287e.jpeg)

**Environment:**

* **Plugin Version**: 1.1.0
* **Homebridge Version**: 1.3.4 
* **Node.js Version**: 14.17.0 
* **NPM Version**: 6.14.13 
* **Operating System**: DietPi 7.1.2 (Raspbian Buster)

**Comment by MrAsterisco** [comment]
Hi @marchein , thanks for reporting this. Unfortunately, this is a known issue and I haven't been able to fix it yet. Basically what seems to be happening is this:

- When turning on the TV, HomeKit makes a call to the plugin to get the list of inputs. When this happens, we don't have the list of inputs yet, because the TV is still turning on.
- As soon as we receive the inputs list, the plugin emits an update with the inputs list, but HomeKit ignores that and just stays on the original input list (it updates some parts of the UI, but not all).

When this happens, just killing and reopening the Home app fixes the problem.

I am already looking into a solution, but haven't found any so far.

**Comment by RobertLowe** [comment]
> When turning on the TV, HomeKit makes a call to the plugin to get the list of inputs. When this happens, we don't have the list of inputs yet, because the TV is still turning on.

my tv is already on, paired and added to homekit; i can neither turn it off or on and input is always unknown

**Comment by LeLunZ** [comment]
Issue is now stale for about 2 years will be closed. 
@marchein If there are any new updates I can reopen it for you.
