### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by ljhudson01** [MrAsterisco/homebridge-hisense-tv#43]
**Describe Your Problem:**
 I have homebridge installed on Pi, but I do not understand how to install any of the dependencies. Do I install Python for windows on my computer?

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by MrAsterisco** [comment]
Hey @ljhudson01 !

You can find the commands you need to give to install the plugin on Windows [here](https://github.com/MrAsterisco/homebridge-hisense-tv#macos--windows). 

In order to have `pip3`, you will have to install Python, yes, together with all the requirements listed [here](https://github.com/MrAsterisco/homebridge-hisense-tv#requirements).

I'm closing this issue now, because the README already contains all the information you're asking for. Feel free to reopen it, if I missed something.

**Comment by ljhudson01** [comment]
Am I installing the windows version of Python, even though my homebridge a small pi?
