### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by ljhudson01** [MrAsterisco/homebridge-hisense-tv#44]
installation instructions 

**Describe Your Problem:**
I am not understanding how to install the dependencies, I am using the windows platform to install plugins but my homebridge on a pi

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

![image](https://user-images.githubusercontent.com/129816990/229938381-58f12c11-81c0-4f4f-b32f-b531b1ee402f.jpeg)
![image](https://user-images.githubusercontent.com/129816990/229938480-45e9d9e6-c362-42ea-bca7-c50c161b9508.jpeg)

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by MrAsterisco** [comment]
Hey @ljhudson01 !

I don't understand why you opened a new issue. 😊 But anyway, if you're running Homebridge on your Rasbperry Pi, you will need to install the dependencies on the Raspberry itself. This means connecting to the Raspberry either directly, with a mouse and keyboard, or via SSH.

I cannot help you further on this, because I do not own a Raspberry Pi, but the procedure should be straightforward.

**Comment by ljhudson01** [comment]
Can you leave this issue open, so someone that understands can help?
I have also been on the homebridge Reddit site and the same questions are asked there.
It's not self explanatory. We have a homebridge plugin and we are having trouble understanding your Readme

**Comment by MrAsterisco** [comment]
I reopened the issue 😊 But, your problem is understanding how to interact with your setup, right? It is not specific of this plugin.

As I already said, you need to install the required dependencies on the machine that is executing Homebridge. You need to login into your Raspberry Pi where you installed Homebridge and install the dependencies, including Python.

Do you know how to log into your Raspberry Pi? If not, I recommend you start from there.

Once again, please let me be super clear: I'm happy to help, but you're having issues with your setup, **not** with this plugin. In any case, I will leave the issue open, if that helps you.

**Comment by LeLunZ** [comment]
@ljhudson01 From what I am getting of this issue: you have problems with installing the dependencies?


Regarding installation of the dependencies, open the terminal on your raspberry pi (over ssh or with a display) and run the install instructions:
`apt install python3-paho-mqtt python3-netifaces`

Then just open your Homebridge website.
Click on the 3 dots.
<img width="145" alt="Screenshot 2024-05-17 at 15 04 59" src="https://github.com/MrAsterisco/homebridge-hisense-tv/assets/31982496/a25988e6-7e4d-4219-ac99-671bded46fc7">

click on terminal
<img width="187" alt="Screenshot 2024-05-17 at 15 06 21" src="https://github.com/MrAsterisco/homebridge-hisense-tv/assets/31982496/7d3347a9-55aa-4eb3-aab9-4d911ad6956c">

use `cd node_modules/homebridge-hisense-tv-remotenow/bin`

<img width="887" alt="Screenshot 2024-05-17 at 15 08 10" src="https://github.com/MrAsterisco/homebridge-hisense-tv/assets/31982496/1bfe5e63-373d-49df-8e59-6f676d822258">

run the authorization:
`python3.8 hisensetv.py <TV_IP_ADDRESS> --authorize --ifname <NETWORK_INTERFACE_NAME>`
(its possible you need to add certificates in that step)


That should be everything.

**Comment by LeLunZ** [comment]
But regarding the first screenshot:
I get similar errors which I want to debug in the coming days
<img width="1264" alt="Screenshot 2024-05-17 at 15 17 04" src="https://github.com/MrAsterisco/homebridge-hisense-tv/assets/31982496/e086fe46-a606-4fe3-95ff-f6cba4aa013d">

**Comment by LeLunZ** [comment]
Closing as this got answered twice now.

- either direclty on your raspberry pi (via monitor, mouse,keyboard) install the dependencies (in the command line) or use ssh to connect to the pi
- Use the homebridge-ui build-in terminal 

If you still need help. Feel free to answer to this comment, and I can help you with your setup.
